name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - development

env:
  DOCKER_HUB_USERNAME: diquzart
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read version
        id: read-version
        run: |
          $ver = Get-Content -Path Container/version
          echo "VERSION=$ver" >> $env:GITHUB_ENV
 
      - name: Print Promtail version
        run: |
          echo "The version is:  $env:VERSION"

      - name: Build Docker image
        run: |
           docker build `
             --build-arg=PROMTAIL_VERSION=${{ $env:VERSION }} `
             --tag=${{ env.DOCKER_HUB_USERNAME }}/promtail-win:${{ $env:VERSION }} `
             -f Container/Containerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
           username: ${{ env.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
           context: .
           file: Container/Containerfile
           push: ${{ env.DOCKER_HUB_USERNAME }}/promtail-win:${{ $env:VERSION }}
